name: word_count
description: A comprehensive multi-language word counting library for Dart supporting 85+ languages including CJK, European, South Asian, African, and Middle Eastern languages.
version: 1.0.1
repository: https://github.com/watate/word_count
homepage: https://github.com/watate/word_count

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  string_stats: ^0.1.0
